/**
 * Book Tracking Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthorResponse { 
    /**
     * The unique identifier (UUID) of the author.
     */
    id?: string;
    /**
     * The name of the author.
     */
    name?: string;
}

