/**
 * Book Tracking Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthorResponse } from './authorResponse';


export interface BookResponse { 
    /**
     * The unique identifier (UUUID) for the book.
     */
    id?: string;
    /**
     * The title of the book.
     */
    title?: string;
    author?: AuthorResponse;
    /**
     * The status of the book (0 - Wishlist 1 - Reading 2 - Read)
     */
    status?: number;
}

